name: nodd
desc: Nodd 2.0 is a new version of Official SCJ Discord Bot. Nodd bot is originally for Numbering Server members, but now has integrated functions.
version: 2.1.0
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  nyxx: ^2.1.2
  nyxx_interactions: ^2.0.3
  pointycastle: ^3.4.0
  http: ^0.13.3
  intl: ^0.17.0
  gsheets: ^0.3.2

# dev_dependencies:
#   dp_common_dart_linters:
#     git:
#       url: https://github.com/DevelopersPackages-org/dp_common_linters
#       path: Dart_Linters
